### ISSUE TITLE
Feature request: Null object export

### ISSUE THREAD

**Issue by tomcypher89** [adroitwhiz/after-effects-to-blender-export#1]
Awesome tool, big thanks! This would become an ultimate camera export tool if there was an option to export one or several nulls as well (to know, where to place your 3d stuff in blender later on)

**Comment by jcnwholland** [comment]
Yes please, that would be great.. happy to donate

**Comment by myllep** [comment]
Any chance there will be further development on exporting null objects? That would make the difference!

**Comment by adroitwhiz** [comment]
I've added support for exporting null objects in the latest release--let me know if you encounter any issues or if there are any missing features that would be helpful for your use case.

**Comment by jcnwholland** [comment]
thank you amice! I'll test it out right now. Where can i leave a donation?

**Comment by adroitwhiz** [comment]
[Here's a donation link](https://www.paypal.com/donate?business=ZMXQWFPPT78V2&no_recurring=1&currency_code=USD)--don't feel obligated to donate, though!

**Comment by jcnwholland** [comment]
A did a 10 usd donation as token of gratitude, gr
