### ISSUE TITLE
Error exporting layer "Main Camera" On line 1305: undefined is not an object

### ISSUE THREAD

**Issue by Goobethiake** [adroitwhiz/after-effects-to-blender-export#10]
**Describe the bug**

**Error message**
```
Error message goes here
```

**To Reproduce**

**Screenshots**

**Test Case**

**Additional context**

**Comment by adroitwhiz** [comment]
I assume you're trying to export a camera layer. I have a few questions:
- What version of After Effects are you using?
- Does the camera layer have a "Point of Interest" set?
- Can you share the .aep file that causes the problem, or a stripped-down version of it that still reproduces the bug?

**Comment by adroitwhiz** [comment]
Closing this as I can't reproduce this and there's been no response
