### ISSUE TITLE
Tracking data doesnt get exported as .json

### ISSUE THREAD

**Issue by fujinplus** [adroitwhiz/after-effects-to-blender-export#13]
I installed the script in after effects on a macbook air m1 and it works (kinda). 
The exported file doesnt get saved as .json
Is this because I am on MacOS?

**Comment by adroitwhiz** [comment]
Possibly. I use Windows, so I haven't had an opportunity to test any of the functionality on macOS. Does the file have any extension when saved?

You should still be able to import it into Blender--click on the funnel-shaped icon in the top-right corner of the file picker, and it'll disable filtering by file extension, allowing you to see non-.json files.

**Comment by adroitwhiz** [comment]
I've updated the AE script to always set the file extension to .json.
