### ISSUE TITLE
Blener Importing json file problem

### ISSUE THREAD

**Issue by mindsetmastery** [adroitwhiz/after-effects-to-blender-export#18]
I'm having trouble locating the exported JSON file from After Effects when attempting to import it into Blender.

**Comment by adroitwhiz** [comment]
See https://github.com/adroitwhiz/after-effects-to-blender-export/issues/13?

**Comment by adroitwhiz** [comment]
Going to assume this is a duplicate of #13, which I've fixed. Feel free to reopen if you can't get this working.
