### ISSUE TITLE
blender 2.92.0 issue, add on

### ISSUE THREAD

**Issue by dcHaptic123** [adroitwhiz/after-effects-to-blender-export#2]
hey, 
i have a problem with the add on in blender, i cant install it because when i do it just nothing happens, it shows me that it was installed but i cant tick the box to activate it, i tried it on many blender versions but it didnt worked. i hope someone can help me,
dcHaptic

**Comment by adroitwhiz** [comment]
Instead of trying to install the entire `.zip` file, try just installing the `import-camera-to-blender.py` file inside it.

**Comment by adroitwhiz** [comment]
@dcHaptic123 Did installing the `import-camera-to-blender.py` file solve your issue?

**Comment by dcHaptic123** [comment]
hey, i solved my problem ,the addon is so good
________________________________
Von: adroitwhiz ***@***.***>
Gesendet: Samstag, 24. Juli 2021 04:57
An: adroitwhiz/after-effects-to-blender-export ***@***.***>
Cc: dcHaptic123 ***@***.***>; Mention ***@***.***>
Betreff: Re: [adroitwhiz/after-effects-to-blender-export] blender 2.92.0 issue, add on (#2)


@dcHaptic123<https://github.com/dcHaptic123> Did installing the import-camera-to-blender.py file solve your issue?

**Comment by adroitwhiz** [comment]
Glad to hear it! I'm going to close this issue; feel free to open another if you encounter any further problems.
