### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by shahariarislamrafi** [adroitwhiz/after-effects-to-blender-export#31]
**Describe the bug**

**Error message**
```
Error message goes here
```

**To Reproduce**

**Screenshots**

**Test Case**

**Platform Info**
- 
- 

**Additional context**

**Comment by shahariarislamrafi** [comment]
best plugin

**Comment by adroitwhiz** [comment]
Hi,

It seems that you have not provided any information about the error message, the file that caused the error, or any other useful information that will allow me to diagnose and fix the error. Feel free to open a new issue providing that information.
