### ISSUE TITLE
ERROR: it says add on is old version huh?

### ISSUE THREAD

**Issue by NickoEfendi12** [adroitwhiz/after-effects-to-blender-export#40]
**Describe the bug**

**Error message**

**To Reproduce**

**Screenshots**

**Test Case**

**Platform Info**
- 
- 

**Additional context**

**Comment by NickoEfendi12** [comment]
![Screenshot 2024-11-23 162935](https://github.com/user-attachments/assets/dfbd1405-6bec-470d-8432-ce791ef41f8c)

**Comment by Tainacds** [comment]
O meu está dando isso também,como resolve? Gosto muito de trabalhar assim com o blender

**Comment by adroitwhiz** [comment]
Hi,

Make sure you have the latest version of "Export Composition Data to JSON.jsx" installed in After Effects.

Are you following a specific online tutorial?

**Comment by Tainacds** [comment]
I updated it, and now it's working again, thank you very much, if you are
the creator, know that you help my work a lot.

Em sáb., 14 de dez. de 2024 07:06, adroitwhiz ***@***.***>
escreveu:
