### ISSUE TITLE
When I import json-model from AE, I have error. Please, check this.

### ISSUE THREAD

**Issue by thgodamn** [adroitwhiz/after-effects-to-blender-export#7]
Python: Traceback (most recent call last):
  File "C:\Users\comp\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\import-comp-to-blender.py", line 341, in execute
    self.import_baked_transform(obj, layer['transform'], transform)
TypeError: ImportAEComp.import_baked_transform() missing 2 required positional arguments: 'desired_framerate' and 'func'

**Comment by adroitwhiz** [comment]
I believe I've fixed this. Can you download and install the latest version of the Blender addon and see if it works now?

**Comment by adroitwhiz** [comment]
I've tested that I can import baked transforms. Closing this issue as it should be fixed.
